### ISSUE TITLE
esque edit & apply doesn't apply changes to partitions and replication

### ISSUE THREAD

**Issue by MrTrustworthy** [kaufland-ecommerce/esque#28]

**Comment by swenzel** [comment]
The replication thing is a little more complicated. Not even "official" topic edit command line tool can do this. You'll have to start a partition reassignment, where every partition gets assigned to the desired number of brokers. Meaning that you'll have to consider balancing if you don't want to assign/remove them randomly.

**Comment by MrTrustworthy** [comment]
Well that sucks. The least we can do for now is failing loudly if the user attempts to change those settings then

**Comment by MrTrustworthy** [comment]
This issue also applies to `esque apply`

**Comment by MrTrustworthy** [comment]
With #27 `esque edit` will no longer show the non-editable properties and `esque apply` will warn that it won't change those settings on existing topics. Removing the "bug" label and adding "enhancement"

**Comment by MrTrustworthy** [comment]
Closing in favour of #45
