### ISSUE TITLE
describe topic doesn't check if topic exists

### ISSUE THREAD

**Issue by garrettthomaskth** [kaufland-ecommerce/esque#49]
(esque) Garretts-MacBook-Pro:esque garrettthomas$ esque describe topic fsdjklhaslhjke
Topic: fsdjklhaslhjke
Config:
  cleanup.policy:                          delete
  compression.type:                        producer
  delete.retention.ms:                     1 day
  file.delete.delay.ms:                    1 minute
  flush.messages:                          9223372036854775807
  flush.ms:                                292471208 years
  follower.replication.throttled.replicas: ''
  index.interval.bytes:                    4.00 kib
  leader.replication.throttled.replicas:   ''
  max.message.bytes:                       976.57 kib
  message.downconversion.enable:           true
  message.format.version:                  2.2-IV1
  message.timestamp.difference.max.ms:     292471208 years
  message.timestamp.type:                  CreateTime
  min.cleanable.dirty.ratio:               0.5
  min.compaction.lag.ms:                   
  min.insync.replicas:                     1
  preallocate:                             false
  retention.bytes:                         None
  retention.ms:                            1 week
  segment.bytes:                           1.00 Gib
  segment.index.bytes:                     10.00 Mib
  segment.jitter.ms:                       
  segment.ms:                              1 week
  unclean.leader.election.enable:          false

**Comment by hfjn** [comment]
So this error just occured because our test environment still had auto creation of topics enabled. It led me to a different error though. Confluent actually always returns a result set on `list_topics` the result for a non existent topic is just an error in that case. Fixed that in my upcoming PR.
