### ISSUE TITLE
Disable Commits in simple consumers

### ISSUE THREAD

**Issue by hfjn** [kaufland-ecommerce/esque#90]
We don't really need consumergroups for the ping consumergroups and probably also for the groups used in #82 and #84.

We can achieve that by [disabling auto-commit in those consumer classes.](https://github.com/confluentinc/confluent-kafka-python/issues/250)

**Comment by cbsmith** [comment]
I'm actually having problems making this work without calling subscribe. I'm trying to read the most recent message from a topic and not having much luck by just doing assign() & seek(). It looks like without subscribe() the fetcher doesn't know what to fetch.

**Comment by swenzel** [comment]
Hard to say what's going on without seeing your code.
What I can say is that, as far as I know, there is no functionality to put your consumer at the last message of a topic with one function call. If you're using the confluent consumer and set `"enable.partition.eof": True` then you'll get a partition EOF message when you call `poll` after you assigned yourself to `OFFSET_END` (assuming there are no new messages coming in). You can then use that message's offset - 1 to put yourself to the offset of the last message.
```python
consumer = Consumer(self._config) # assuming you're inheriting from our AbstractConsumer
consumer.assign([TopicPartition(topic=topic, partition=0, offset=OFFSET_END)])

eof_msg=consumer.poll(timeout=10)

consumer.seek(TopicPartition(topic=topic, partition=0, offset=eof_msg.offset()-1))

last_message = consumer.poll()
```
